### ISSUE TITLE
Cannot run on windows

### ISSUE THREAD

**Issue by icguy** [gtasa-savegame-editor/gtasa-savegame-editor#73] opened 2021-01-30 20:47 UTC
The following exception is being thrown:

```
java.lang.Error: Invalid memory access
        at com.sun.jna.Native.invokeInt(Native Method)
        at com.sun.jna.Function.invoke(Function.java:426)
        at com.sun.jna.Function.invoke(Function.java:361)
        at com.sun.jna.Library$Handler.invoke(Library.java:265)
        at com.sun.proxy.$Proxy0.SHGetSpecialFolderPath(Unknown Source)
        at nl.paulinternet.gtasaveedit.Settings.getSettingsFile(Settings.java:69)
        at nl.paulinternet.gtasaveedit.Settings.<clinit>(Settings.java:23)
        at nl.paulinternet.gtasaveedit.view.window.MainWindow.<init>(MainWindow.java:30)
        at nl.paulinternet.gtasaveedit.view.window.MainWindow.getInstance(MainWindow.java:20)
        at nl.paulinternet.gtasaveedit.view.Main.main(Main.java:55)
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class nl.paulinternet.gtasaveedit.Settings
        at nl.paulinternet.gtasaveedit.view.window.MainWindow.<init>(MainWindow.java:30)
        at nl.paulinternet.gtasaveedit.view.window.MainWindow.getInstance(MainWindow.java:20)
        at nl.paulinternet.gtasaveedit.view.window.ExceptionDialog.<init>(ExceptionDialog.java:47)
        at nl.paulinternet.gtasaveedit.view.Main.main(Main.java:68)
```

editor version: 3.3-SNAPSHOT
java version: 11.0.7

**Comment by lfuelling** [comment] 2021-01-31 12:52
Duplicate of #71

**Closed by lfuelling** 2021-01-31 12:52 UTC
Labels: duplicate
