### ISSUE TITLE
null

### ISSUE THREAD

**Issue by CornholioNeedsRolio** [gtasa-savegame-editor/gtasa-savegame-editor#108] opened 2021-09-04 14:55 UTC
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1368)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1343)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1479)
	at nl.paulinternet.gtasaveedit.view.Main.main(Main.java:68)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "this.loaded" is null
	at nl.paulinternet.gtasaveedit.view.component.TabbedPane.updateUI(TabbedPane.java:110)
	at java.desktop/javax.swing.JTabbedPane.<init>(JTabbedPane.java:231)
	at java.desktop/javax.swing.JTabbedPane.<init>(JTabbedPane.java:196)
	at nl.paulinternet.gtasaveedit.view.component.TabbedPane.<init>(TabbedPane.java:26)
	at nl.paulinternet.gtasaveedit.view.window.MainWindow.createContent(MainWindow.java:49)
	at nl.paulinternet.gtasaveedit.view.GUICreator.run(GUICreator.java:23)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:306)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at nl.paulinternet.gtasaveedit.view.EventQueueProxy.dispatchEvent(EventQueueProxy.java:14)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by lfuelling** [comment] 2021-09-05 00:46
This is a duplicate of  #107.

**Closed by lfuelling** 2021-09-05 00:46 UTC
